Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/10/2021
Var
// Seção de Declarações das variáveis 
N1, N2, Soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("N1")
leia(N1)
escreval("N2")
leia(N2)
Soma <- N1+N2:
escreval("Soma",Soma)

Fimalgoritmo