Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/10/2021
Var
// Seção de Declarações das variáveis 
a,b,aux: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("A",a)
leia (a)
escreval ("B",b)
leia (b)
escreval ("B",b)
escreval ("A",a)

Fimalgoritmo